GET http://localhost:7777/api/user/orders HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTc4NjQzODAsInVzZXJfaWQiOiLQktCw0YHRjzExIn0.Im-GuGefDVFuvrMiB6XwW-LKcXRpHtePeX4iIIuyi0U