GET http://localhost:7777/api/user/orders HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTc3NTA5NDksInVzZXJfaWQiOiLQktCw0YHRjyJ9.HsNPgghHSEcvolJPM50L9KeNqJFKnapCP5JqDBpuebQ