POST http://localhost:7777/api/user/orders HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTc4NjYyMDMsInVzZXJfaWQiOiLQktCw0YHRjzExMjMifQ.szEC8YvJsrhXHD3BThYCbgLVjZtUWFFpSQDC6qxVpe4
content-type: text/plain

5060916250