POST http://localhost:7777/api/user/balance/withdraw HTTP/1.1
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTc4NTM2NDgsInVzZXJfaWQiOiLQktCw0YHRjzExMjMifQ.fhfZgVk_CqzAvrDC8biSt0oAYfHekpIPYvnwUv-LBrk
content-type: application/json

{
    "order": "6768946243",
    "sum": 2.43
}